apiVersion: apps/v1
kind: Deployment
metadata:
  name: rum-teste-frontend
  labels:
    app: rum-teste-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rum-teste-frontend
  template:
    metadata:
      labels:
        app: rum-teste-frontend
    spec:
      containers:
      - name: rum-teste-frontend
        image: vinicpires/rum-teste-frontend:SHORT_SHA
        ports:
        - containerPort: 80
--- 

apiVersion: v1
kind: Service
metadata:
  name: rum-teste-frontend-service
  labels:
    app: rum-teste-frontend
spec:
  selector:
    app: rum-teste-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

--- 

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rum-teste-frontend-ingress
 # annotations:
   # nginx.ingress.kubernetes.io/rewrite-target: /
   # cert-manager.io/cluster-issuer: "cloudflare-cluster-issuer"
spec:
  rules:
    - host: rum-frontend.lab4ever.xyz 
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rum-teste-frontend-service
                port:
                  number: 80
  tls:
    - hosts:
        - rum-frontend.lab4ever.xyz
      secretName: cloudflare-origin-cert
